import rtconfig
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))
           ]
# src = Split("""
# main.cpp,

# """)
# src = [Glob('*.c'), Glob('*.cpp')]
src = Glob('*.cpp')+Glob('*.c')

group = DefineGroup('Applications', src, depend=[''], CPPPATH=CPPPATH)

Return('group')

# # for module compiling
# import os
# from building import *

# cwd = GetCurrentDir()
# objs = []
# list = os.listdir(cwd)

# for d in list:
#     path = os.path.join(cwd, d)
#     if os.path.isfile(os.path.join(path, 'SConscript')):
#         objs = objs + SConscript(os.path.join(d, 'SConscript'))

# Return('objs')
