from building import *
Import('RTT_ROOT')
Import('rtconfig')

cwd = GetCurrentDir()
src = Glob('*.c')+Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Util_libs', src, depend=[''], CPPPATH=CPPPATH)

Return('group')
